```{r}
library(tidyverse)
library(jsonlite)
library(mapdeck)
```

```{r}
mapbox <- read_json("../data/mapbox.json")
set_token(mapbox$token)
```

```{r}
providers <- read_csv("../data/tn_providers.csv", show_col_types = F)
hop_teaming <- read_csv("../data/tn_hop_teaming.csv", show_col_types = F)
addresses <- read_csv("../data/tn_team_hopping_addresses.csv", show_col_types = F)
```

```{r}
npi_lat_long <- providers %>% 
  inner_join(addresses %>% drop_na(geo_address),
             by = c("address_first_line", 
                    "address_second_line", 
                    "city", 
                    "state", 
                    "zipcode")) %>%
  select(npi, lat, long)

write_csv(npi_lat_long, "../data/npi_lat_long.csv")
```

```{r}
hop_teaming_lat_long <- hop_teaming %>% 
  inner_join(npi_lat_long %>% rename_with(~paste0("from_", .x)), by = "from_npi") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("to_", .x)), by = "to_npi")

write_csv(hop_teaming_lat_long, "../data/hop_teaming_lat_long.csv")
```

```{r}
mapdeck(style = mapdeck_style("light"), pitch = 60) %>%
  add_animated_arc(
    data = hop_teaming_lat_long %>% sample_n(500), 
    layer_id = "arc_layer", 
    origin = c("from_long", "from_lat"), 
    destination = c("to_long", "to_lat"), 
    stroke_from = "from_npi", 
    stroke_to = "to_npi",
    stroke_width = 1,
    brush_radius = 80467)
```

```{r}
hop_teaming_provider_to_facility_patient_counts <- read_csv("../data/hop_teaming_provider_to_facility_patient_counts.csv", show_col_types = F)
npi_lat_long <- read_csv("../data/npi_lat_long.csv", show_col_types = F)
```

```{r}
df <- hop_teaming_provider_to_facility_patient_counts %>% 
  filter(from_cbsa == 34980, 
         to_affiliation %in% c("VUMC", "HCA", "ASCENSION SAINT THOMAS", "OTHER"),
         from_specialty == "Orthopaedic Surgery") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("from_", .x)), by = "from_npi") %>%
  inner_join(npi_lat_long %>% rename_with(~paste0("to_", .x)), by = "to_npi") %>%
  mutate(from_hex = case_when(to_affiliation == "VUMC" ~ "#9a783d01",
                              to_affiliation == "HCA" ~ "#e2592901",
                              to_affiliation == "ASCENSION SAINT THOMAS" ~ "#1c429701",
                              to_affiliation == "OTHER" ~ "#aaaaaa01"),
         to_hex = case_when(to_affiliation == "VUMC" ~ "#9a783d80",
                            to_affiliation == "HCA" ~ "#e2592980",
                            to_affiliation == "ASCENSION SAINT THOMAS" ~ "#1c429780",
                            to_affiliation == "OTHER" ~ "#aaaaaa80"))
```

```{r}
mapdeck(style = mapdeck_style("dark"), pitch = 60) %>%
  add_grid(
    data = df %>% filter(to_affiliation == "VUMC"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#9a783d","#9a783d","#9a783d","#9a783d","#9a783d","#9a783d"),
    cell_size = 500,
    elevation_scale = 25,
    layer_id = "VUMC") %>%
  add_grid(
    data = df %>% filter(to_affiliation == "HCA"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#e25929","#e25929","#e25929","#e25929","#e25929","#e25929"),
    cell_size = 500,
    elevation_scale = 25,
    layer_id = "HCA") %>%
  add_grid(
    data = df %>% filter(to_affiliation == "ASCENSION SAINT THOMAS"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#1c4297","#1c4297","#1c4297","#1c4297","#1c4297","#1c4297"),
    cell_size = 500,
    elevation_scale = 25,
    layer_id = "ASCENSION SAINT THOMAS") %>%
  add_grid(
    data = df %>% filter(to_affiliation == "OTHER"),
    lat = "from_lat",
    lon = "from_long",
    colour_range = c("#aaaaaa","#aaaaaa","#aaaaaa","#aaaaaa","#aaaaaa","#aaaaaa"),
    cell_size = 500,
    elevation_scale = 25,
    layer_id = "OTHER") %>%
  add_animated_arc(
    data = df %>% sample_n(200), 
    layer_id = "arc_layer", 
    origin = c("from_long", "from_lat"), 
    destination = c("to_long", "to_lat"), 
    stroke_from = "from_hex", 
    stroke_to = "to_hex",
    animation_speed = 0.1,
    stroke_width = 2)
```



